server {
    listen 80;
    listen [::]:80;

    server_name ~^.*$;

    include snippets/error-pages.conf;

    # Let's Encrypt ACME challenge
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # Wszystko inne → przekierowanie na HTTPS zachowując host
    location / {
        return 301 https://$host$request_uri;
    }

    access_log /var/log/nginx/access_www.acme_challenge.log;
    error_log  /var/log/nginx/error_www.acme_challenge.log;
}
