server {
    listen 80;
    listen [::]:80;

    server_name _;   # catch-all dla wszystkich domen

    # Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/cert_challenge/.well-known/acme-challenge;
        allow all;
    }

    # Wszystko inne → przekierowanie na HTTPS zachowując host
    location / {
        return 301 https://$host$request_uri;
    }
}
