server {
    listen 80;
    listen [::]:80;

    server_name www.{subdomain}.{domain} {subdomain}.{domain};

    include snippets/error-pages.conf;

    location = / {
      return 200 'ok';
      add_header Content-Type text/plain;
    }

    # Logs
    access_log /var/log/nginx/access_www.{subdomain}.{domain}.log;
    error_log  /var/log/nginx/error_www.{subdomain}.{domain}.log;
}
server {
    server_name www.{subdomain}.{domain} {subdomain}.{domain};

    include snippets/https-def.conf;          # Comment out for dev
    ssl_certificate     /etc/ssl/certs/www.{subdomain}.{domain}.crt;
    ssl_certificate_key /etc/ssl/certs/www.{subdomain}.{domain}.key;
    # If you use certbot for creating certificate, uncomment these lines and comment out the above two lines
    #ssl_certificate     /var/www/ssl_certificates/www.{subdomain}.{domain}/fullchain.pem;
    #ssl_certificate_key /var/www/ssl_certificates/www.{subdomain}.{domain}/privkey.pem;

    include snippets/error-pages.conf;

    location = / {
      return 200 'ok';
      add_header Content-Type text/plain;
    }
    # Logs
    access_log /var/log/nginx/access_www.{subdomain}.{domain}.log;
    error_log  /var/log/nginx/error_www.{subdomain}.{domain}.log;
}