server {
    listen 80;
    listen [::]:80;

    server_name www.{subdomain}.{domain} {subdomain}.{domain};  # domain with "www"

    include snippets/error_pages.conf;

    location = / {
      return 200 'ok';
      add_header Content-Type text/plain;
    }

    # Logs
    access_log /var/log/nginx/access_www.{subdomain}.{domain}.static.log;
    error_log  /var/log/nginx/error_www.{subdomain}.{domain}.static.log;
}
