server {
    server_name {subdomain}.{domain} {subdomain}.{domain};

    include snippets/http-def.conf;
    include snippets/error-pages.conf;

    # Uncomment for Let's Encrypt ACME challenge
    # include snippets/acme-challenge.conf;

    location = / {
      return 200 'ok';
      add_header Content-Type text/plain;
    }

    # Logs
    access_log /var/log/nginx/access_{subdomain}.{domain}.log;
    error_log  /var/log/nginx/error_{subdomain}.{domain}.log;
}
server {
    server_name {subdomain}.{domain};

    include snippets/https-def.conf;          # Comment out for dev
    ssl_certificate     /etc/ssl/certs/{subdomain}.{domain}.crt;
    ssl_certificate_key /etc/ssl/certs/{subdomain}.{domain}.key;
    # If you use certbot for creating certificate, uncomment these lines and comment out the above two lines
    #ssl_certificate     /etc/letsencrypt/live/{subdomain}.{domain}/fullchain.pem;
    #ssl_certificate_key /etc/letsencrypt/live/{subdomain}.{domain}/privkey.pem;

    include snippets/error-pages.conf;

    location = / {
      return 200 'ok';
      add_header Content-Type text/plain;
    }
    # Logs
    access_log /var/log/nginx/access_{subdomain}.{domain}.log;
    error_log  /var/log/nginx/error_{subdomain}.{domain}.log;
}