# ================================================
# Nginx configuration template for reverse proxy
# Replace: {domain}, {subdomain}
# ================================================

# ------------------------------------------------
# 1️⃣ Redirect http to https
# ------------------------------------------------
server {
    server_name {subdomain}.{domain}

    include snippets/http-def.conf;

    # Uncomment for Let's Encrypt ACME challenge
    # include snippets/acme-challenge.conf;

    location / {
      # Redirect all requests to https://
      return 301 https://$host$request_uri;
    }
    access_log /var/log/nginx/access_http_{subdomain}.log;
    error_log /var/log/nginx/error_http_{subdomain}.log;
 }

# ------------------------------------------------
# 2️⃣ Main server block
# - Prod: include snippets/https-def.conf and SSL certificates
# - Dev: include snippets/http-def.conf and comment out SSL lines
# ------------------------------------------------
server {
    server_name {subdomain}.{domain}; 

    # --------------------
    # Production (HTTPS)
    # --------------------
    include snippets/https-def.conf;          # Comment out for dev
    ssl_certificate     /etc/ssl/certs/{subdomain}.{domain}.crt;
    ssl_certificate_key /etc/ssl/certs/{subdomain}.{domain}.key;
    # If you use certbot for creating certificate, uncomment these lines and comment out the above two lines
    #ssl_certificate     /etc/letsencrypt/live/{subdomain}.{domain}/fullchain.pem;
    #ssl_certificate_key /etc/letsencrypt/live/{subdomain}.{domain}/privkey.pem;

    # --------------------
    # Development (HTTP)
    # --------------------
    # include snippets/http-def.conf;         # Uncomment for dev/localhost

    client_max_body_size 50M;
    include snippets/error-pages.conf;

    root /var/www/phpmyadmin;
    index index.php index.html;

    # you can include some extra configuration file
    #include /var/www/phpmyadmin/var/nginx/server.conf;

    location ~* \.php$ {
      fastcgi_pass phpmyadmin:9000;
      include fastcgi_params;
      fastcgi_param PATH_INFO       $fastcgi_path_info;
      fastcgi_param DOCUMENT_ROOT   /var/www/html;  # <-- application root directory in the container
      fastcgi_param SCRIPT_FILENAME /var/www/html/$fastcgi_script_name;

      # you can overwrite some php-ini parameters
      #fastcgi_param PHP_ADMIN_VALUE "error_log=/var/www/logs/{YOUR_DOMAIN}-php-error.log;upload_max_filesize = 6M;";
      # you can set custom parameters
      #fastcgi_param APPLICATION_LOGS_DIR  /var/www/logs/phpmyadmin;
      #fastcgi_param APPLICATION_CACHE_DIR /var/www/cache/phpmyadmin;
      #fastcgi_param APPLICATION_DATA_DIR  /var/www/data/phpmyadmin;
    }

    # Logs
    access_log /var/log/nginx/access_{subdomain}.{domain}.proxy.log;
    error_log  /var/log/nginx/error_{subdomain}.{domain}.proxy.log;
}
