server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;   # tu i tak nie ma znaczenia, bo to default_server

    root /var/www/src/default;

    include snippets/error-pages.conf;
    include snippets/static-files.conf;

    location / {
        return 404;
    }

    access_log /var/log/nginx/access_default.log main;
    error_log /var/log/nginx/error_default.log;
}
# fallback default_server dla wszystkich nieznanych domen lub wejść na IP
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;     # IPv6
    server_name _;  # catch-all

    # fake cert (self-signed, np. CN=invalid.local)
    ssl_certificate     /etc/ssl/fallback/fake.crt;
    ssl_certificate_key /etc/ssl/fallback/fake.key;

    # od razu kończymy połączenie lub zwracamy 404
    return 444;  # zamyka połączenie bez odpowiedzi
    # return 404; # alternatywnie możesz zwrócić 404
}
